###功能类

###获取协调者节点
GET http://localhost:8080/coordinator

###获取协调者节点
GET http://localhost:8080/rebalanceFinished


###示例类

###SqlFieldsQuery域查询
GET http://localhost:8080/sqlFieldsQuery

###SqlQuery查询
GET http://localhost:8080/sqlQuery

###根据key查询value
GET http://localhost:8080/getByKey


###分布式计算
###broadcast
GET http://localhost:8080/broadcast
###call
GET http://localhost:8080/call
###apply
GET http://localhost:8080/apply
###affinity
GET http://localhost:8080/affinity
###
GET http://localhost:8080/affinity2
###MapReduce
GET http://localhost:8080/taskMap
###
GET http://localhost:8080/taskSplit


###mybatis ignite
###单表查询
GET http://localhost:8080/mybatis/findStudentsById?studentId=6

###
###多表联查
GET http://localhost:8080/mybatis/findGradeByName?name=student_6

###
GET http://localhost:8080/mybatis/cpFindStudentsById?studentId=6

###

